name: myapp
description: "A waste recycling system"
publish_to: 'none' 

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # Utility packages
  http: ^1.2.2
  intl: ^0.20.1
  logger: ^2.5.0
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.4
  path_provider: ^2.1.5
  smooth_page_indicator: ^1.2.0+3
  lottie: ^3.3.1
  connectivity_plus: ^5.0.1
  fl_chart: ^0.70.2
  syncfusion_flutter_charts: ^28.2.12
  
  # Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

  # Storage
  shared_preferences: ^2.5.1
  cloud_firestore: ^5.6.3
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0

  # State management
  get: ^4.6.6
  get_storage: ^2.1.1
  
  # Google fonts & UI components
  google_fonts: ^6.2.1
  flutter_heatmap_calendar: ^1.0.5
  google_maps_flutter: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting for best practices  
  flutter_lints: ^5.0.0

  # Mock Firebase & Dependencies for Testing  
  mockito: ^5.4.4
  fake_cloud_firestore: ^3.1.0
  firebase_auth_mocks: ^0.14.1
  google_sign_in: ^6.3.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/illustrations/
    - assets/logos/
