// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2-HB9_TZ-aBTH8j2twR1w644voERvZ6E',
    appId: '1:24448036818:web:287167d81576544de6220b',
    messagingSenderId: '24448036818',
    projectId: 'myapp-11c3a',
    authDomain: 'myapp-11c3a.firebaseapp.com',
    storageBucket: 'myapp-11c3a.firebasestorage.app',
    measurementId: 'G-GQ1JZDWL7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwT2BJkRe-lBmu2NNpgY_tOM_MdIqeA3w',
    appId: '1:24448036818:android:7ed6120dc20f6a84e6220b',
    messagingSenderId: '24448036818',
    projectId: 'myapp-11c3a',
    storageBucket: 'myapp-11c3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzQUS1wu9Wkm-2AxzCShzfTILUgwKu73c',
    appId: '1:24448036818:ios:76947462a5c97784e6220b',
    messagingSenderId: '24448036818',
    projectId: 'myapp-11c3a',
    storageBucket: 'myapp-11c3a.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzQUS1wu9Wkm-2AxzCShzfTILUgwKu73c',
    appId: '1:24448036818:ios:76947462a5c97784e6220b',
    messagingSenderId: '24448036818',
    projectId: 'myapp-11c3a',
    storageBucket: 'myapp-11c3a.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2-HB9_TZ-aBTH8j2twR1w644voERvZ6E',
    appId: '1:24448036818:web:e648b4a4a06e5ba3e6220b',
    messagingSenderId: '24448036818',
    projectId: 'myapp-11c3a',
    authDomain: 'myapp-11c3a.firebaseapp.com',
    storageBucket: 'myapp-11c3a.firebasestorage.app',
    measurementId: 'G-T46KET55HC',
  );
}
